url: http://math.andrej.com
name: Mathematics and Computation
description: A blog about mathematics for computers

kramdown:
  hard_wrap: false
  input: Markdown
  math_engine:

exclude:
  - staticman.yml
  - publish.sh
  - Gemfile
  - Gemfile.lock
  - README.markdown
  - etc/

plugins:
  - jekyll-archives
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-feed

staticman:
  branch: "master"
  username: "andrejbauer"
  repository: "mathematics-and-computation"
  site: "http://lisa.andrej.com:1984"

paginate: 10

paginate_path: "page-:num/"

permalink: /:year/:month/:day/:slug/

jekyll-archives:
  enabled:
    - categories
    - year
  layouts:
    year: archive-year
    category: archive-category
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
