url: http://math.andrej.com
name: Mathematics and Computation
description: Mathematics for computers

kramdown:
  hard_wrap: false
  input: Markdown
  math_engine: nil

exclude:
  - publish.sh
  - Gemfile
  - Gemfile.lock
  - README.markdown
  - etc/

plugins:
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
    - year
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'